apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: far-chickadee-go 
  janus-idp.io/tekton: far-chickadee-go
  backstage.io/kubernetes-id: far-chickadee-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: far-chickadee-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  